# Generated by Django 4.2.5 on 2023-09-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_countries_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='uf',
            field=models.CharField(max_length=4),
        ),
    ]
